### ISSUE TITLE
[Bug] - Ensure reclaim script is functional

### ISSUE THREAD

**Issue by setbern** [stacks-network/sbtc#789] opened 2024-11-07 14:17 UTC
Currently reclaim script is left in the dark and needs to be tested. 

Acceptance Criteria: Sender is able to reclaim bitcoin sent if the deposit script was not able to be picked up.

**Comment by aldur** [comment] 2024-11-28 16:35
Duplicate of #936

**Closed by aldur** 2024-11-28 16:35 UTC
Labels: bridge web app
