### ISSUE TITLE
[DR] Romeo does not seem to pick up on transactions if it has been running for a while

### ISSUE THREAD

**Issue by kenrogers** [stacks-network/sbtc#272] opened 2023-10-12 16:31 UTC
### Expected Behavior

Romeo successfully detects and processes transactions.

### Actual Behavior

Romeo detects the transaction but says that a transaction was broadcasted that is not acknolwedged.

### Steps to Reproduce

I'm not 100% sure on the cause here. But I had the sbtc devenv running for a while, and initiated a deposit transaction. It did not detect it, so I took down the sbtc container and spun it back up. It then processed the next deposit I made, but also returned an error.

### Screenshots or Videos
<img width="1489" alt="image" src="https://github.com/stacks-network/sbtc/assets/7418051/57eb9447-399b-48ee-a464-60603ece6542">

**Comment by friedger** [comment] 2023-10-12 17:58
This is a duplicate of https://github.com/stacks-network/sbtc/issues/268

**Closed by friedger** 2023-10-12 17:58 UTC
Labels: bug
