### ISSUE TITLE
[DR] sBTC deposit transaction not minting sBTC in devenv

### ISSUE THREAD

**Issue by kenrogers** [stacks-network/sbtc#220] opened 2023-10-04 17:35 UTC
### Expected Behavior

When running devenv and initiating a deposit using the `deposit.sh` helper, a mint transaction would be triggered on the stacks chain.

### Actual Behavior

The deposit transaction is created and broadcasted successfully to the bitcoin regtest network, but no corresponding mint transaction occurs on the stacks chain.

### Steps to Reproduce

1. Follow setup steps according to devenv README to get containers built and running
2. Change the mnemonic in `config.json` to match Devnet deployer address
3. Deploy contracts using `deploy_contracts.sh`
4. Mine 200 BTC with `mine_btc.sh 200`
5. Initiate deposit with `deposit.sh`
6. Transaction shows in Bitcoin Explorer but no sBTC mint function follows

### Screenshots or Videos
On running `log.sh sbtc` I do see this error after the Stacks chain begins mining blocks
<img width="1252" alt="image" src="https://github.com/stacks-network/sbtc/assets/7418051/c7b3ecb6-853a-481d-ad30-abee5ce566e6">

Here is a screen share of my process:

https://github.com/stacks-network/sbtc/assets/7418051/0f65b852-be74-47db-a805-7df73d9f29f9

**Comment by friedger** [comment] 2023-10-04 18:20
@kenrogers As a work around you can probably call `sbtc/down.sh` and `sbtc/up.sh`

It looks like the problem is that the engine expects the the contract to be deployed at startup but the devenv does not deploy the contacts.

Maybe we want to ring back the deployment of the contracts through stbc. 

CC @CAGS295

**Comment by CAGS295** [comment] 2023-10-04 19:07
@EmbeddedAndroid, you may find some overlap in here #215. [This](https://github.com/stacks-network/sbtc/pull/215/files#diff-56bb3d9e8d0e342d456dd54468938fb905f8bea8793ddf7d3393d04a15c28661R9-R25) is how I do it.

**Comment by kenrogers** [comment] 2023-10-04 20:47
@friedger @EmbeddedAndroid 

Seeing a new error in the logs after trying `docker-compose down sbtc` followed by `docker-compose up -d sbtc`

<img width="1075" alt="image" src="https://github.com/stacks-network/sbtc/assets/7418051/cb8020d7-33ef-4467-a0bc-e53bcd8c2b55">

**Comment by CAGS295** [comment] 2023-10-05 00:24
@kenrogers, try reproducing the error with #222 applied and tell me what happens. Also, could you share the value used in this step? 
> Change the mnemonic in `config.json` to match Devnet deployer address

**Comment by friedger** [comment] 2023-10-05 04:27
@EmbeddedAndroid for the contract deployment, we could bring back this function to the engine.

The engine could check whether the contract exists and if not deploy it. What do you think? We have the code in the git history.

**Comment by friedger** [comment] 2023-10-05 04:32
Actually, the deploy script is much better suitable.

**Comment by janniks** [comment] 2023-10-05 13:53
Could the contract deploy be a part of the docker-compose up? Is that what you mean by bringing it to the engine?

**Comment by kenrogers** [comment] 2023-10-05 14:38
Success 🙌🏻 

<img width="1014" alt="image" src="https://github.com/stacks-network/sbtc/assets/7418051/42e93f70-257a-4c0f-8598-718f92b27f48">

**Comment by friedger** [comment] 2023-10-12 15:14
Closing this as the mint works on devnet.  The deployment is handled in #231

**Closed by friedger** 2023-10-12 15:14 UTC
Labels: bug, alpha-romeo, devenv
